In [1]:
import numpy as np

In [38]:
state = np.zeros((8, 8), dtype=int)

In [150]:
class Othero():
    
    def __init__(self, N=8):
        self.set_board()
        self.current_turn = 1
        self.length_board = N

    def set_board(self):
        board = np.zeros((8, 8), dtype=int)
        i = 3
        j = 4
        board[i,i] = board[j,j] = 1
        board[j,i] = board[i,j] = -1
        self.state = board

    def display(self):
        print(self.state)
    
    def _change_state(self, new_stone_loc:tuple):
        """change state for each direction"""
        count_reverse = 0
        i, j = new_stone_loc
        opposite = -1* self.current_turn
        state = np.copy(self.state)
        # dx, dy を使う方針に転換する。 18:02
        for direction in ["row", "col", "diag", "anti-diag"]:
            for dir_ in [1, -1]:
                count_reverse = 0
                for d in range(self.length_board):
                    print(d)
                    try:
                        dx, dy = self.set_direction(dir_*d,direction)
                        # 縦横斜めどう制御する？
                        if state[i + dx, j + dy] == opposite:
                            count_reverse += 1
                        elif state[i + dx, j + dy] == 0:
                            count_reverse = 0
                            break
                        elif state[i + dx, j + dy] == self.current_turn:
                            break
                    except IndexError:
                        break
                if count_reverse > 0:
                    print("we can reverse", count_reverse, "piece(s)!")
                    for d in range(1, count_reverse+1):
                        dx, dy = self.set_direction(dir_*d, direction)
                        state[i + dx, j + dy] = self.current_turn 
        self.current_turn = -1*self.current_turn
        self.state = state
    def set_direction(self, d, direction):
        if direction == "row":
            dx = d
            dy = 0
        elif direction == "col":
            dx = 0
            dy = d
        elif direction == "diag":
            dx = -1*d
            dy = d     
        elif direction == "anti-diag":
            dx = d
            dy = -1*d
        return dx, dy 


In [151]:
othero = Othero()
othero

In [152]:
othero._change_state((2,3))
othero.display()

0
0
0
0
0
0
0
0
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


In [149]:
# othero.display()

In [58]:
i = 3
j = 4
state[i,i] = 1
state[j,j] = 1
state[i,j] = -1
state[j,i] = -1

In [59]:
state[3,2] = -1
state[3:]

array([[ 0,  0, -1,  1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [104]:
i = 3
j = 2
N = 8 # length of the bourd
state[i,:]
state[i,0:j]
# left side
if j != 0 and state[i,j-1] ==0:
    # do nothing
    pass

# right side
if j != 8 and state[i,j+1] ==0:
    # do nothing
    pass

turn = -1
count_reverse = 0
opposite = -1* turn
for j_ in range(j+1,N):
    try
    print(state[i, j_])
    if state[i, j_] == opposite:
        count_reverse += 1
    elif state[i, j_] == 0:
        count_reverse = 0
        break
    elif state[i, j_] == turn:
        break
if count_reverse > 0:
    print("we can reverse", count_reverse, "piece(s)!")
    for c_r in range(1, count_reverse+1):
        state[i, j + c_r] = turn
# state

-1


In [ ]:
for d in range(N):
    try:
        dx, dy = self.set_direction(d)
        # 縦横斜めどう制御する？
        if state[i + dx, j + dy] == opposite:
            count_reverse += 1
        elif state[i + dx, j + dy] == 0:
            count_reverse = 0
            break
        elif state[i + dx, j + dy] == turn:
            break
    except IndexError:
        pass
if count_reverse > 0:
    print("we can reverse", count_reverse, "piece(s)!")
    for d in range(1, count_reverse+1):
        dx, dy = self.set_direction(d)
        state[i + dx, j + dy] = turn


Scraps

In [86]:
for c_r in range(1, count_reverse+1):
    state[i, j + c_r] = turn

In [102]:
np.diag(np.rot90(state,axes=(0, 1)))
np.diag(state, k=abs(i-j))[2]

0

In [96]:
np.flip(state.T,axis=0)

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, -1,  1,  0,  0,  0],
       [ 0,  0,  0, -1, -1,  0,  0,  0],
       [ 0,  0,  0, -1,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

In [156]:

a = np.eye(10)

In [173]:
print(" "*6+"_".join(list(map(str, range(10)))))
for i, r_ in enumerate(a):
    print(str(i)+" | "+str(r_))

      0_1_2_3_4_5_6_7_8_9
0 | [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1 | [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
2 | [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
3 | [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
4 | [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
5 | [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
6 | [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
7 | [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
8 | [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
9 | [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [168]:
"_".join(list(map(str, range(10))))

'0_1_2_3_4_5_6_7_8_9'